import { z } from "zod"

/**
 * The public spare-parts catalogue's search parameters.
 *
 * ── Why parsing is forgiving rather than strict ───────────────────────
 * Everything here arrives in a query string, which is user-editable,
 * bookmarked, pasted into WhatsApp, and rewritten by link previewers. A
 * malformed value is an ordinary event, not an exceptional one, so each field
 * falls back to "not filtered" rather than throwing: `?page=banana` shows page
 * one, `?category=nonsense` shows every part.
 *
 * That is *not* the same as trusting the input. Every value that survives is
 * length-bounded and type-checked before it reaches Prisma, and the query
 * layer parameterises it — so a category slug containing a quote is a value
 * that matches nothing, never syntax.
 *
 * ── The two ways a customer narrows the catalogue ─────────────────────
 * `category` is the rail of chips at the top of the page. It carries the
 * category's *slug*, not its id: a slug is stable, readable in a shared link,
 * and survives a database restore into a fresh environment where ids differ.
 * Absent means "All", which is the default — the page opens showing
 * everything.
 *
 * `q` is the search box beneath it: one field matched against the part name,
 * the manufacturer's number and our own reference at once, so someone holding
 * an old part can type what is stamped on it without first deciding which
 * kind of number it is.
 *
 * The two combine rather than compete — a category chip and a search term are
 * ANDed by the query layer.
 */

/**
 * Upper bound on the category slug.
 *
 * The rail only ever emits slugs that exist, so a legitimate value is short.
 * The cap is aimed at a hand-edited URL carrying kilobytes into a query.
 */
const CATEGORY_SLUG_MAX_LENGTH = 60

/**
 * A category slug as it arrives from the URL.
 *
 * Empty and whitespace-only collapse to `undefined`, which is what the "All"
 * chip means — and what a GET form submits for an unselected control.
 *
 * The character class is deliberately narrow. Slugs are generated by
 * `slugifyFragment`, so anything outside `[a-z0-9-]` was not produced by this
 * application; refusing it here means the value never reaches a query at all.
 */
const categoryFilter = z
  .string()
  .trim()
  .toLowerCase()
  .max(CATEGORY_SLUG_MAX_LENGTH)
  .regex(/^[a-z0-9-]*$/)
  .transform((value) => (value.length === 0 ? undefined : value))
  .optional()
  .catch(undefined)

/**
 * Upper bound on the free-text search box.
 *
 * Long enough for "toyota harrier front brake pads", short enough that a
 * pasted paragraph never reaches the database. Over the limit the term is
 * dropped entirely (`.catch`), which shows the unfiltered catalogue rather
 * than an error page.
 */
const SEARCH_TERM_MAX_LENGTH = 80

/**
 * The free-text query.
 *
 * Whitespace is trimmed *and* collapsed, so "brake   pads" and "brake pads"
 * are one URL rather than two addresses for one result set.
 */
const searchTerm = z
  .string()
  .trim()
  .max(SEARCH_TERM_MAX_LENGTH)
  .transform((value) => value.replace(/\s+/g, " "))
  .transform((value) => (value.length === 0 ? undefined : value))
  .optional()
  .catch(undefined)

/**
 * The page number.
 *
 * Separate from the filters below because it is not one: it does not narrow
 * the result set, and every filter change resets it.
 */
const pageFilter = z
  .union([z.string(), z.number()])
  .transform((value) => {
    const parsed = Number(typeof value === "number" ? value : value.trim())

    return Number.isInteger(parsed) && parsed > 0 ? parsed : 1
  })
  .catch(1)
  .default(1)

export const sparePartSearchSchema = z.object({
  q: searchTerm,
  category: categoryFilter,
  page: pageFilter,
})

export type SparePartSearchParams = z.infer<typeof sparePartSearchSchema>

/** Just the narrowing part — what the query layer turns into a where clause. */
export type SparePartSearchCriteria = Omit<SparePartSearchParams, "page">

/**
 * Parses a Next.js `searchParams` object.
 *
 * A value arrives as `string | string[] | undefined`: a URL may legally repeat
 * a key, and `?category=brakes&category=engine` is not a filter the rail can
 * represent. The first occurrence wins, which matches what a browser submits
 * from a form and what the links below build.
 */
export function parseSparePartSearchParams(
  params: Record<string, string | string[] | undefined>
): SparePartSearchParams {
  const first = (value: string | string[] | undefined) =>
    Array.isArray(value) ? value[0] : value

  return sparePartSearchSchema.parse({
    q: first(params.q),
    category: first(params.category),
    page: first(params.page) ?? 1,
  })
}

/** True when at least one narrowing filter is active. */
export function hasActivePartSearch(criteria: SparePartSearchCriteria): boolean {
  return Boolean(criteria.q || criteria.category)
}

/**
 * Rebuilds a catalogue query string from criteria plus an optional page.
 *
 * One builder for the category rail, the search box, the pagination links and
 * the clear control, so a filtered page-two link cannot lose its filters.
 * Keys are emitted in a fixed order and empty values are omitted, so the same
 * search always produces the same URL — which matters for caching and for not
 * showing a customer two addresses for one result set.
 */
export function buildPartCatalogueQuery(
  criteria: SparePartSearchCriteria,
  page = 1
): string {
  const params = new URLSearchParams()

  if (criteria.category) params.set("category", criteria.category)
  if (criteria.q) params.set("q", criteria.q)
  // Page one is the default and is left out, so "/spare-parts" and
  // "/spare-parts?page=1" do not become two URLs for the same page.
  if (page > 1) params.set("page", String(page))

  return params.toString()
}

/** `/spare-parts` with the criteria applied. */
export function partCatalogueHref(
  criteria: SparePartSearchCriteria,
  page = 1
): string {
  const query = buildPartCatalogueQuery(criteria, page)

  return query ? `/spare-parts?${query}` : "/spare-parts"
}
