-- Rate-limiting store for administrator sign-in (SECURITY.MD §5.5).
--
-- Written by hand rather than generated by `prisma migrate dev`, which
-- refuses to run against this database: Supabase installs its own extensions
-- (pg_stat_statements, pgcrypto, uuid-ossp, supabase_vault) that the Prisma
-- schema does not declare, so `migrate dev` reads them as drift and offers to
-- reset the schema. Resetting a live database holding real inventory is not
-- an option. `prisma migrate deploy` applies this file without drift
-- detection, which is also how it will be applied in CI and production.
--
-- Additive only: one new table, no changes to any existing table, so this is
-- safe to apply to a live database. Creating a table takes no lock on
-- anything already there.

-- CreateTable
CREATE TABLE "LoginAttempt" (
    "id" TEXT NOT NULL,
    "identifierHash" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LoginAttempt_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
-- The limiter's only read: count rows for one key newer than a cutoff.
-- Equality columns first, range column last, so the window is an index range
-- scan rather than a filter applied over the whole bucket.
CREATE INDEX "LoginAttempt_scope_identifierHash_createdAt_idx" ON "LoginAttempt"("scope", "identifierHash", "createdAt");

-- CreateIndex
-- Supports the housekeeping delete that prunes rows past every window.
CREATE INDEX "LoginAttempt_createdAt_idx" ON "LoginAttempt"("createdAt");
